# Generated by Django 5.2.12 on 2026-04-20 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_workspaceinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Markdown description of rules and program goals')),
                ('scope', models.JSONField(default=list, help_text='List of assets in scope')),
                ('rewards', models.JSONField(default=dict, help_text='Mapping of severity to reward amount')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Ativo'), ('PAUSED', 'Pausado'), ('CLOSED', 'Encerrado')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_programs', to='users.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BountySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Crítico'), ('HIGH', 'Alto'), ('MEDIUM', 'Médio'), ('LOW', 'Baixo'), ('INFO', 'Informativo')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('TRIAGED', 'Triado'), ('NEGOTIATING', 'Em Negociação'), ('RESOLVED', 'Resolvido'), ('DUPLICATE', 'Duplicado'), ('OUT_OF_SCOPE', 'Fora de Escopo'), ('REJECTED', 'Rejeitado')], default='NEW', max_length=20)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('proof_token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('proof_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='bounty.bountyprogram')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
