# Generated by Django 5.2.12 on 2026-04-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountysubmission',
            name='target_domain',
            field=models.CharField(default='', help_text='The specific domain/asset being verified for proof of possession', max_length=255),
        ),
    ]
