# Generated by Django 5.2.12 on 2026-06-19 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_bountysubmission_target_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountysubmission',
            name='compliance_certificate',
            field=models.FileField(blank=True, help_text='Generated PDF compliance certificate', null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='bountysubmission',
            name='compliance_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping to security standards (OWASP, MITRE, etc.)'),
        ),
        migrations.AddField(
            model_name='bountysubmission',
            name='technical_details',
            field=models.JSONField(blank=True, default=dict, help_text='Structured technical artifacts for audit trail'),
        ),
        migrations.AddField(
            model_name='bountysubmission',
            name='verification_hash',
            field=models.CharField(blank=True, help_text='SHA-256 fingerprint for audit integrity', max_length=64),
        ),
        migrations.AddField(
            model_name='bountysubmission',
            name='visual_proof_b64',
            field=models.TextField(blank=True, help_text='Screenshot of the vulnerability provided by researcher', null=True),
        ),
        migrations.CreateModel(
            name='BountyAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='evidence/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='MIME type or category (PCAP, LOG, BIN)', max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(help_text='SHA-256 hash of the file content', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bounty.bountysubmission')),
            ],
        ),
    ]
