# Generated by Django 5.2.12 on 2026-04-24 09:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('users', '0002_workspaceinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('credits', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('credits', models.IntegerField()),
                ('bonus_credits', models.IntegerField(default=0)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('badge_text', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('max_per_workspace_per_month', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'credit_packages',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AITransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('debit_from_subscription', models.IntegerField(default=0)),
                ('debit_from_purchased', models.IntegerField(default=0)),
                ('debit_from_bonus', models.IntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('balance_before', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('mode', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], default='standard', max_length=20)),
                ('mode_multiplier', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=3)),
                ('tokens_input', models.IntegerField(blank=True, null=True)),
                ('tokens_output', models.IntegerField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('revenue_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('was_cached', models.BooleanField(default=False)),
                ('cache_hit_key', models.CharField(blank=True, default='', max_length=255)),
                ('reference_type', models.CharField(blank=True, default='', max_length=100)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_charge_id', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_transactions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_transactions', to='users.workspace')),
            ],
            options={
                'db_table': 'ai_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='idx_aitx_workspace_date'), models.Index(fields=['type', 'action'], name='idx_aitx_type_action'), models.Index(condition=models.Q(('stripe_payment_intent_id__gt', '')), fields=['stripe_payment_intent_id'], name='idx_aitx_stripe')],
            },
        ),
        migrations.CreateModel(
            name='AIWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_subscription', models.IntegerField(default=0, help_text='Credits from monthly plan grant. Expire at period end.')),
                ('balance_purchased', models.IntegerField(default=0, help_text='Credits bought via packages. Never expire.')),
                ('balance_bonus', models.IntegerField(default=0, help_text='Credits from achievements/referrals. Never expire.')),
                ('lifetime_credits_granted', models.IntegerField(default=0)),
                ('lifetime_credits_used', models.IntegerField(default=0)),
                ('lifetime_revenue_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('auto_reload_enabled', models.BooleanField(default=False)),
                ('auto_reload_threshold', models.IntegerField(default=100)),
                ('auto_reload_package', models.CharField(blank=True, default='', help_text='Slug of the CreditPackage to auto-buy.', max_length=50)),
                ('auto_reload_stripe_pm', models.CharField(blank=True, default='', help_text='Stripe PaymentMethod ID for auto-reload.', max_length=255)),
                ('low_balance_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('zero_balance_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_months_active', models.IntegerField(default=0)),
                ('rollover_credits', models.IntegerField(default=0)),
                ('express_mode_enabled', models.BooleanField(default=False)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_wallet', to='users.workspace')),
            ],
            options={
                'db_table': 'ai_wallets',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance_subscription__gte', 0)), name='ck_ai_wallet_sub_gte_0'), models.CheckConstraint(condition=models.Q(('balance_purchased__gte', 0)), name='ck_ai_wallet_purch_gte_0'), models.CheckConstraint(condition=models.Q(('balance_bonus__gte', 0)), name='ck_ai_wallet_bonus_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCreditGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('credits_granted', models.IntegerField()),
                ('rollover_added', models.IntegerField(default=0)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_grants', to='billing.subscription')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_credit_grants', to='users.workspace')),
            ],
            options={
                'db_table': 'monthly_credit_grants',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'period_start'), name='uq_monthly_grant_workspace_period')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('credits_awarded', models.IntegerField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='ai.achievement')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.workspace')),
            ],
            options={
                'db_table': 'workspace_achievements',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'achievement'), name='uq_workspace_achievement')],
            },
        ),
    ]
