# Generated by Django 5.2.12 on 2026-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_seed_packages_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
