'use client';

import { useState } from 'react';
import { verifyReportHash } from '@/lib/api';
import { ShieldCheck, Search, FileText, Calendar, Target, Hash, Loader2, CheckCircle2, XCircle } from 'lucide-react';
import Link from 'next/link';

export default function VerifyPage() {
  const [hash, setHash] = useState('');
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleVerify = async (e?: React.FormEvent) => {
    e?.preventDefault();
    if (!hash || hash.length < 10) return;

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const data = await verifyReportHash(hash);
      setResult(data);
    } catch (err: any) {
      setError(err.message || 'Report not found or invalid hash.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-black text-foreground font-mono flex flex-col items-center justify-center p-6 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')]">
      <div className="w-full max-w-2xl">
        <div className="text-center mb-10 animate-in fade-in slide-in-from-top-4 duration-700">
          <div className="inline-flex items-center justify-center p-3 rounded-2xl bg-neon-green/10 border border-neon-green/20 mb-6">
            <ShieldCheck className="w-12 h-12 text-neon-green" />
          </div>
          <h1 className="text-4xl font-bold tracking-tighter mb-2 uppercase">Integrity Portal</h1>
          <p className="text-gray-500 text-sm uppercase tracking-[0.3em]">HackerScan Pro Cryptographic Verification</p>
        </div>

        <div className="bg-[#0a0a0a] border border-white/5 rounded-2xl p-8 shadow-2xl shadow-neon-green/5 animate-in fade-in slide-in-from-bottom-4 duration-700 delay-150">
          <form onSubmit={handleVerify} className="space-y-6">
            <div className="space-y-2">
              <label className="text-[10px] text-gray-500 uppercase tracking-widest ml-1 font-bold">Report Digital Signature (SHA-256)</label>
              <div className="relative group">
                <Hash className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-600 group-focus-within:text-neon-green transition-colors" />
                <input 
                  type="text"
                  placeholder="ENTER 64-CHARACTER SIGNATURE..."
                  value={hash}
                  onChange={(e) => setHash(e.target.value)}
                  className="w-full bg-black border border-white/10 rounded-xl pl-12 pr-4 py-4 focus:outline-none focus:border-neon-green/50 transition-all text-sm tracking-widest placeholder:text-gray-800"
                />
              </div>
            </div>

            <button 
              type="submit"
              disabled={loading || hash.length < 10}
              className="w-full bg-white text-black font-bold py-4 rounded-xl hover:bg-neon-green hover:text-black transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:hover:bg-white"
            >
              {loading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  AUTHENTICATING...
                </>
              ) : (
                <>
                  <Search className="w-5 h-5" />
                  VERIFY AUTHENTICITY
                </>
              )}
            </button>
          </form>

          {error && (
            <div className="mt-8 p-6 rounded-xl bg-red-500/5 border border-red-500/10 flex items-start gap-4 animate-in zoom-in-95">
              <XCircle className="w-6 h-6 text-red-500 shrink-0" />
              <div>
                <h3 className="text-red-500 font-bold text-sm uppercase">Verification Failed</h3>
                <p className="text-gray-400 text-xs mt-1">This signature does not match any record in our secure ledger. The report may have been tampered with or was not generated by HackerScan Pro.</p>
              </div>
            </div>
          )}

          {result && (
            <div className="mt-8 p-6 rounded-xl bg-neon-green/5 border border-neon-green/10 flex flex-col gap-6 animate-in zoom-in-95">
              <div className="flex items-start gap-4">
                <CheckCircle2 className="w-6 h-6 text-neon-green shrink-0" />
                <div>
                  <h3 className="text-neon-green font-bold text-sm uppercase">Authenticity Confirmed</h3>
                  <p className="text-gray-400 text-xs mt-1">Digital signature verified. This report is an authentic cryptographic artifact generated by HackerScan Pro.</p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4 border-t border-white/5">
                <div className="space-y-1">
                   <div className="text-[9px] text-gray-600 uppercase font-bold">Target Infrastructure</div>
                   <div className="flex items-center gap-2 text-xs">
                     <Target className="w-3 h-3 text-blue-500" />
                     {result.target}
                   </div>
                </div>
                <div className="space-y-1">
                   <div className="text-[9px] text-gray-600 uppercase font-bold">Generation Date</div>
                   <div className="flex items-center gap-2 text-xs">
                     <Calendar className="w-3 h-3 text-purple-500" />
                     {new Date(result.timestamp).toLocaleString()}
                   </div>
                </div>
                <div className="space-y-1">
                   <div className="text-[9px] text-gray-600 uppercase font-bold">Report Type</div>
                   <div className="flex items-center gap-2 text-xs">
                     <FileText className="w-3 h-3 text-orange-500" />
                     {result.type} ({result.format})
                   </div>
                </div>
                <div className="space-y-1">
                   <div className="text-[9px] text-gray-600 uppercase font-bold">Artifact ID</div>
                   <div className="flex items-center gap-2 text-xs text-gray-500 italic">
                     {result.report_id}
                   </div>
                </div>
              </div>
            </div>
          )}
        </div>

        <div className="mt-12 text-center text-[10px] text-gray-600 space-y-4">
           <p className="uppercase tracking-[0.2em]">Secured by HackerScan Pro Distributed Ledger</p>
           <div className="flex items-center justify-center gap-6">
              <Link href="/login" className="hover:text-neon-green transition-colors uppercase">System Login</Link>
              <span className="text-gray-800">|</span>
              <a href="#" className="hover:text-neon-green transition-colors uppercase">Documentation</a>
              <span className="text-gray-800">|</span>
              <a href="#" className="hover:text-neon-green transition-colors uppercase">API Verify</a>
           </div>
        </div>
      </div>
    </div>
  );
}
