# Generated by Django 5.2.12 on 2026-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SCAN_COMPLETED', 'Scan Completed'), ('VULNERABILITY_FOUND', 'Vulnerability Found'), ('BILLING_ALERT', 'Billing Alert'), ('SYSTEM_UPDATE', 'System Update'), ('AUDIT_TAMPERING', 'Audit Tampering Detected')], max_length=50),
        ),
    ]
