# Generated by Django 5.2.12 on 2026-04-25 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_workspaceinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.workspace'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['workspace', '-created_at'], name='idx_audit_ws_created'),
        ),
    ]
