# Generated by Django 6.0.3 on 2026-05-12 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditlog_workspace_auditlog_idx_audit_ws_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='current_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='idx_audit_action_created'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['current_hash'], name='idx_audit_hash'),
        ),
    ]
