# Generated by Django 6.0.3 on 2026-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Type-specific configuration (e.g. Jira project key, Auth tokens)'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='type',
            field=models.CharField(choices=[('GENERIC', 'Generic Webhook'), ('SLACK', 'Slack (Rich Blocks)'), ('JIRA', 'Jira Issue Creation'), ('SPLUNK', 'Splunk HEC')], default='GENERIC', help_text='Integration type for payload formatting.', max_length=20),
        ),
    ]
