# Generated by Django 5.2.12 on 2026-04-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitymodule',
            name='config_schema',
            field=models.JSONField(default=dict, help_text='JSON schema for module-specific configuration options'),
        ),
    ]
