# Generated by Django 6.0.3 on 2026-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="scan_type",
            field=models.CharField(
                choices=[
                    ("quick", "Quick Scan (Nmap + Headers)"),
                    ("full", "Full Security Scan (Nuclei + All Plugins)"),
                    ("vuln", "Vulnerability Research (Nuclei)"),
                    ("recon", "Recon & Subdomains (Subfinder)"),
                    ("ssl", "SSL/TLS Audit (SSLyze)"),
                    ("fuzz", "Directory Fuzzing (Gobuster)"),
                    ("discovery", "Resource Discovery (BS4 + Custom)"),
                ],
                db_index=True,
                default="quick",
                max_length=20,
            ),
        ),
    ]
