# Generated by Django 6.0.3 on 2026-04-21 06:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("scans", "0002_scan_scan_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="first_seen_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="finding",
            name="last_seen_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="finding",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("resolved", "Resolved"),
                    ("fixed", "Fixed"),
                    ("suppressed", "Suppressed"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="scan_type",
            field=models.CharField(
                choices=[
                    ("quick", "Quick Scan (Nmap + Headers)"),
                    ("full", "Full Security Scan (Nuclei + All Plugins)"),
                    ("vuln", "Vulnerability Research (Nuclei)"),
                    ("recon", "Recon & Subdomains (Subfinder)"),
                    ("ssl", "SSL/TLS Audit (SSLyze)"),
                    ("fuzz", "Directory Fuzzing (Gobuster)"),
                    ("discovery", "Resource Discovery (BS4 + Custom)"),
                    ("ad_audit", "Active Directory Tactical Audit"),
                    ("k8s_security", "Kubernetes Hardening & Security"),
                    ("sap_audit", "SAP Ecosystem Recon"),
                ],
                db_index=True,
                default="quick",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ScheduledScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("quick", "Quick Scan (Nmap + Headers)"),
                            ("full", "Full Security Scan (Nuclei + All Plugins)"),
                            ("vuln", "Vulnerability Research (Nuclei)"),
                            ("recon", "Recon & Subdomains (Subfinder)"),
                            ("ssl", "SSL/TLS Audit (SSLyze)"),
                            ("fuzz", "Directory Fuzzing (Gobuster)"),
                            ("discovery", "Resource Discovery (BS4 + Custom)"),
                            ("ad_audit", "Active Directory Tactical Audit"),
                            ("k8s_security", "Kubernetes Hardening & Security"),
                            ("sap_audit", "SAP Ecosystem Recon"),
                        ],
                        default="quick",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "periodic_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_scan",
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="scans.scantarget",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("target", "scan_type")},
            },
        ),
    ]
