# Generated by Django 5.2.12 on 2026-04-22 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_finding_first_seen_at_finding_last_seen_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='epss_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='TargetCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Admin Login', 'API Token'", max_length=255)),
                ('cred_type', models.CharField(choices=[('basic_auth', 'Basic Authentication'), ('header', 'HTTP Header'), ('cookie', 'Cookie'), ('oauth2', 'OAuth2 / Bearer Token')], max_length=20)),
                ('value', models.JSONField(help_text='Credential data (keys vary by type)')),
                ('is_active', models.BooleanField(default=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='scans.scantarget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
