# Generated by Django 5.2.12 on 2026-04-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_finding_epss_score_targetcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='ai_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
