# Generated by Django 5.2.12 on 2026-04-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_finding_ai_reasoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the vulnerability has been manually or automatically verified'),
        ),
        migrations.AddField(
            model_name='finding',
            name='poc',
            field=models.TextField(blank=True, help_text='Actionable Proof of Concept (e.g. curl command or python script)'),
        ),
        migrations.AddField(
            model_name='finding',
            name='request',
            field=models.TextField(blank=True, help_text='The raw HTTP request that triggered the finding'),
        ),
        migrations.AddField(
            model_name='finding',
            name='response',
            field=models.TextField(blank=True, help_text='The raw HTTP response received'),
        ),
        migrations.AddField(
            model_name='scan',
            name='ml_risk_classification',
            field=models.CharField(blank=True, help_text="e.g. 'Low', 'Medium', 'High', 'Critical'", max_length=50),
        ),
        migrations.AddField(
            model_name='scan',
            name='ml_risk_score',
            field=models.FloatField(blank=True, help_text='AI-calculated risk score for this specific scan (0.0 to 100.0)', null=True),
        ),
        migrations.AddField(
            model_name='scantarget',
            name='ml_risk_classification',
            field=models.CharField(blank=True, help_text="e.g. 'Low', 'Medium', 'High', 'Critical'", max_length=50),
        ),
        migrations.AddField(
            model_name='scantarget',
            name='ml_risk_score',
            field=models.FloatField(blank=True, help_text='AI-calculated risk score (0.0 to 100.0)', null=True),
        ),
    ]
