# Generated by Django 5.2.12 on 2026-05-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_finding_is_verified_finding_poc_finding_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='ai_confidence',
            field=models.FloatField(blank=True, help_text="AI's confidence score (0-1) that this is NOT a false positive", null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='user_verification',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('confirmed_valid', 'Confirmed Valid'), ('confirmed_fp', 'Confirmed False Positive')], db_index=True, default='unverified', max_length=20),
        ),
    ]
