# Generated by Django 6.0.4 on 2026-05-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0007_finding_ai_confidence_finding_user_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="report_file",
            field=models.FileField(
                blank=True, null=True, upload_to="scan_reports/%Y/%m/%d/"
            ),
        ),
    ]
