# Generated by Django 5.2.12 on 2026-05-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_scan_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='compliance_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='OWASP Top 10, MITRE ATT&CK and PCI-DSS compliance mapping'),
        ),
        migrations.AddField(
            model_name='finding',
            name='technical_details',
            field=models.JSONField(blank=True, default=dict, help_text='Structured technical artifacts for audit readiness'),
        ),
        migrations.AddField(
            model_name='finding',
            name='visual_proof_b64',
            field=models.TextField(blank=True, help_text='Base64 encoded screenshot of the vulnerability', null=True),
        ),
    ]
