# Generated by Django 5.2.12 on 2026-04-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('JSON', 'JSON'), ('CSV', 'CSV'), ('HTML', 'HTML')], max_length=10),
        ),
    ]
