# Generated by Django 6.0.3 on 2026-06-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='integrity_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash for report verification', max_length=64, null=True),
        ),
    ]
