[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --reuse-db --strict-markers --ignore=scratch --ignore=test_db_conn.py --ignore=test_debug_output.txt --ignore=test_output.txt --ignore=test_output_2.txt
norecursedirs = scratch node_modules venv
